displayName=Boss Kill Milestones
author=Razza98
description=Make every grind count with escalating original jingles, boss kill goals, a progress overlay and a friends hiscore leaderboard.
tags=boss,kill count,milestone,jingle,goals,tracker,overlay,friends,hiscores,leaderboard
version=1.0.1
plugins=com.bosskillmilestones.BossKillMilestonesPlugin
build=standard
